---
- name: Setup wg-portal
  hosts: all
  tags:
    - wireguard
    - wg-portal
  become: true
  tasks:
    - name: enable ipv4 traffic forwarding
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: "1"
        sysctl_set: true
    - name: enable ipv6 traffic forwarding
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "1"
        sysctl_set: true
    # additionally set sysctl config via systemd, because of this weird bug
    # https://bugs.launchpad.net/ubuntu/+source/procps/+bug/50093
    - name: enably ip forwarding on all interfaces via systemd sysctl.d
      ansible.builtin.copy:
        content: |
          net.ipv4.conf.all.forwarding=1
          net.ipv6.conf.all.forwarding=1
        dest: /etc/sysctl.d/ip-forwarding.conf
  roles:
    - role: caddy
    - role: wg_portal
      wg_portal_mail:
        host: mail.your-server.de
        port: 465
        encryption: ssl
        cert_validation: true
        auth_type: plain
        from: Wireguard Portal Merse 88b <no-reply@merse88b.de>
        username: "{{ vault_wg_portal_mail_smtp_username }}"
        password: "{{ vault_wg_portal_mail_smtp_password }}"
        link_only: false
        allow_peer_email: false
      wg_portal_web_external_domain: wg.merse88b.de
      wg_portal_web_site_company_name: Merse 88b
      wg_portal_basic_auth_user: merse
